# Generated by Django 4.0.4 on 2022-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=100)),
                ('english', models.ManyToManyField(to='training.eng')),
            ],
        ),
    ]
