# Generated by Django 4.0.4 on 2022-05-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_current_test_type_current_type_increment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
