# Generated by Django 4.0.4 on 2022-05-22 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0009_alter_current_tested_words_alter_result_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('results', models.CharField(default=[1, 0, 1, 0, 1, 0, 1, 0, 1, 0], max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexicon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
