# Generated by Django 4.0.4 on 2022-05-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_lexicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicon',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lexicon',
            name='percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='lexicon',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
