# Generated by Django 4.0.4 on 2022-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_alter_lexicon_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicon',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
