# Generated by Django 4.0.4 on 2022-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_lexicon_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='last_word_eng',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='current',
            name='last_word_rus',
            field=models.IntegerField(default=0),
        ),
    ]
