# Generated by Django 4.0.4 on 2022-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_current_last_word_eng_current_last_word_rus'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicon',
            name='test_type',
            field=models.CharField(choices=[('ER', 'ER'), ('RE', 'RE')], default='ER', max_length=2),
        ),
    ]
