# Generated by Django 4.0.4 on 2022-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_lexicon_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicon',
            name='word_id',
            field=models.IntegerField(default=0),
        ),
    ]
