# Generated by Django 4.0.4 on 2022-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_lexicon_word_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='last_word_eng',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='current',
            name='last_word_rus',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
