# Generated by Django 4.0.4 on 2022-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_alter_current_last_word_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='last_word_eng',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='current',
            name='last_word_rus',
            field=models.IntegerField(default=0),
        ),
    ]
