# Generated by Django 4.0.4 on 2022-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_alter_current_last_word_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='ff',
            field=models.IntegerField(default=0),
        ),
    ]
