# Generated by Django 4.0.4 on 2022-05-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_current_ff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='ff',
        ),
    ]
